---
abstract: 'Modular access to Getopt::Long'
author:
  - 'Darin McBride <dmcbride@cpan.org>'
build_requires:
  Contextual::Return: v0.2.1
  Exception::Class: 0
  List::MoreUtils: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Getopt-Modular
provides:
  Getopt::Modular:
    file: lib/Getopt/Modular.pm
    version: 0.04
recommends:
  Text::Table: 0
  Text::Wrap: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
